name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Get Dependencies
        run: go get -v -t -d ./...

      - name: Generate JSONs
        run: make generate-jsons

      - name: Test Types
        run: TEST_PKG=./types/... make test

      - name: Test QBFT
        run: TEST_PKG=./qbft/... make test

      - name: Test SSV
        run: TEST_PKG=./ssv/... make test

      - name: Test DKG
        run: TEST_PKG=./dkg/... make test
